export type Post = {
  id: number;
  title: string;
  thumbnail: string;
  images: string[];
  address: string;
  description: string;
  price: number;
  area: number;
  bedrooms: number;
  bathrooms: number;
  direction: string;
  legal_status: string;
  furniture: string;
  status: "available" | "sold";
  is_approved: boolean;
  is_featured: boolean;
  expired_at: string;
  user_id: number;
  type_id: number;
  approved_by: number | null;
  created_at: string;
  updated_at: string;
};